input_data:
  ResearchName: binance_extreme
  dirpath:
    - mktdata
    - binance
    - downloads
  start_date: '2022-08-15T00:00:00'
  selected_instruments:
    - AAVEUSDT
    - ADAUSDT
    - AVAXUSDT
    - BNBUSDT
    - BTCUSDT
    - DOGEUSDT
    - DOTUSDT
    - ETHUSDT
    - MATICUSDT
    - XRPUSDT
run_parameters:
  unit_test: false
  cross_ewma: false
  models:
    quantized_zscore:
      RandomForestClassifier:
        splits_for_1000: 5
        params:
          min_samples_split: 10
          n_jobs: -1
          warm_start: false
          class_weight: balanced_subsample
          oob_score: true
feature_map:
  close:
    ewma_expansion:
      cross_ewma: false
      weight_by: volume
      windows:
        - 1
        - 5
        - 15
        - 60
        - 240
        - 480
        - 1440
        - 4320
    max_expansion:
      windows:
        - 5
        - 15
        - 60
        - 480
        - 1440
        - 4320
    min_expansion:
      windows:
        - 5
        - 15
        - 60
        - 480
        - 1440
        - 4320
    hvol_expansion:
      incr_window:
        - [1, 60]
        - [15, 4320]
      quantiles:
        - 0.35
        - 0.65
        - 1.0
  volume:
    transform: log
    ewma_expansion:
      windows:
        - 5
        - 1440
      quantiles:
        - 0.35
        - 0.65
        - 1.0
  taker_buy_volume:
    transform: arctanh
  close_premium:
    ewma_expansion:
      weight_by: volume
      windows:
        - 5
        - 1440
      quantiles:
        - 0.35
        - 0.65
        - 1.0
label_map:
  quantized_zscore:
    horizons:
      - 60
    stdev_buckets:
      big_down:
        - -999
        - -3
      small_down:
        - -3
        - -1
      0-ish:
        - -1
        - 1
      small_up:
        - 1
        - 3
      big_up:
        - 3
        - 999
strategy:
  type: max_loss_probability
  params:
    class_deltas:
      big_down: -100
      small_down: 0
      0-ish: 0
      small_up: 0
      big_up: 100
    max_loss_probability: 1
backtest:
  tx_cost: 0