input_data:
  ResearchName: defillama
  dirpath:
  - data
  - DynLst
  selected_instruments: all # this comes from top n ever
#  - "883ba955-323f-4c0a-8a53-2e914be7bb39" # pancakeswap-amm-v3_WSTETH-WETH
#  - "5685fa0d-a7cf-4b60-9b77-ff23b4583f81" # uniswap-v3_RETH-WETH
#  - "45ec4aa9-c1db-46ce-ab74-9c78a2b17a48" # aura_WETH-SWETH
#  - "98463e86-e32c-4998-830c-ccd47dbb3041" # aura_WSTETH-WETH
#  - "ecd0c563-8aa2-423e-b8e9-d3259a316df9" # uniswap-v3_WSTETH-WETH
#  - "473a2c92-cc86-4f86-b380-85141bcec627" # uniswap-v3_CBETH-WETH
#  - "d9e834a1-c6f0-44a4-a45c-b80d40318837" # curve-dex_ETH-CBETH
#  - "64e26366-3582-439c-b1de-b7cf84cf2749" # uniswap-v3_WETH-SWETH
#  - "f8931ddf-5ef0-4eb6-9ddf-718cd3f1a172" # uniswap-v3_STETH-WETH
#  - "498dd436-58b1-41c4-bde9-981ced59203b" # pancakeswap-amm-v3_RETH-WETH
#  - "0dd4c573-a3c6-4c35-9bc3-d618aacbc58c" # curve-dex_RETH-FRXETH
#  - "3046ac00-53f7-4ad5-b1f8-c323501d4d3e" # convex-finance_ETH-CBETH
#  - "ad69ffab-73be-4900-9c85-e76089f514f0" # balancer-v2_WSTETH-CBETH
#  - "5455e498-1ca6-4f36-80f4-cf6a2f977c51" # curve-dex_WETH-FRXETH
#  - "5685fa0d-a7cf-4b60-9b77-ff23b4583f81" # uniswap-v3_RETH-WETH
#  - "98463e86-e32c-4998-830c-ccd47dbb3041" # aura_WSTETH-WETH
#  - "64e26366-3582-439c-b1de-b7cf84cf2749" # uniswap-v3_WETH-SWETH
#  - "e36002fe-047b-439a-9d83-2873f41825e9" # pancakeswap-amm-v3_CBETH-WETH
#  - "a4b5b995-99e7-4b8f-916d-8940b5627d70" # aura_RETH-WETH
#  - "93f893b3-fa07-42a2-bfb8-b237501288e7" # aura_WSTETH-CBETH
#  - "b4beb796-4904-457f-9d6f-083ef08aaeba" # pancakeswap-amm-v3_FRXETH-WETH
#  - "3c5c184e-a207-4a89-a625-fa1664d45c7e" # uniswap-v3_OETH-WETH
#  - "ecd0c563-8aa2-423e-b8e9-d3259a316df9" # uniswap-v3_WSTETH-WETH
#  - "30f3b82f-07db-4b92-8657-1ebb277dc23b" # convex-finance_RETH-FRXETH
#  - "ce70e358-6668-498c-9afa-651f770eac27" # aura_WSTETH-SFRXETH-RETH
#  - "8b55f2ca-0f4b-4dbd-8d02-62e8bc397fb9" # curve-dex_WSTETH-RETH-SFRXETH
#  - "e144a863-8013-49d4-8c3c-637ffd415308" # uniswap-v2_STETH-WETH
  start_date: '2022-09-15T00:00:00'
run_parameters:
  normalize: false
  cross_ewma: false
  groupby: false
  models:
    apy:
      TrivialEwmPredictor:
        params:
          cap: 3 # stdev threshold of outlier yield
          halflife: 7d # ewm window for prediction
          horizon: 99y # horizon for depeg conversion to apy
  pickle_file: engine.pickle
  unit_test: false
feature_map: # each feature present here will be transformed. times are in days.
  apy:
    as_is:
  tvl:
    as_is:
  underlying1:
    as_is:
  underlying2:
    as_is:
  underlying3:
    as_is:
label_map:
  apy:
    horizons: # only first is used for now
    - 28
strategy:
  cost: 0.0005 # 1e-4 is a bp
  gas: 20 # in $
  base_buffer: 0.1 # relative to wealth
  concentration_limit: 0.4
  initial_wealth: 100000
  solver_params:
    solver: "ECOS"
    verbose: false
    warm_start: false
    max_iters: 1000
    abstol: 0.01
    reltol: 0.01
    feastol: 0.01
backtest:
  start_date: '2022-12-01T00:00:00'
  end_date: '2023-12-01T00:00:00'
