input_data:
  ResearchName: defillama
  dirpath:
  - singularity
  - midfreq
  - scrappers
  - defillama_history
  - data
  - DynLst
  selected_instruments: # this comes from top n ever
  - "42c02674-f7a2-4cb0-be3d-ade268838770" # balancer-v2_RETH-WETH
  - "4cc5df76-f81d-49fe-9e1e-4caa6a8dad0b" # balancer-v2_WSTETH-WETH
  - "5ce23e7e-3800-4c9c-ad30-6db3db0515a1" # convex-finance_ETH-STETH
  - "747c1d2a-c668-4682-b9f9-296708a3dd90" # lido_STETH
  - "77020688-e1f9-443c-9388-e51ace15cc32" # frax-ether_SFRXETH
  - "c9873dab-0979-478c-b48c-3c3a0c935449" # convex-finance_STETH-FRXETH
  - "d4b3c522-6127-4b89-bedf-83641cdcd2eb" # rocket-pool_RETH
  - "e378a7c2-6285-4993-9397-87ac9c8adc15" # convex-finance_ETH-STETH
  - "e6435aae-cbe9-4d26-ab2c-a4d533db9972" # aave-v3_WSTETH
  - "f1a22245-a1f1-4389-8ff2-dde4914b272d" # aave-v3_RETH
  - "fc7701fc-e290-4606-a8be-9e4ba6c5f91a" # convex-finance_ETH-RETH
#  - "e72916f7-a2d1-47ad-a4b9-2b054337cfd6" # instdapp morpho
  start_date: '2022-06-15T00:00:00'
run_parameters:
  normalize: false
  cross_ewma: false
  groupby: false
  models:
    apy:
      TrivialEwmPredictor:
        params:
          cap: 0.1 # cap applied to outlier yield
          halflife: 7d # ewm window for prediction
  pickle_file: engine.pickle
  unit_test: false
feature_map: # each feature present here will be transformed. times are in days.
  haircut_apy:
    as_is:
label_map:
  apy:
    horizons: # only first is used for now
    - 10
strategy:
  cost: 0.001 # 1e-4 is a bp
  gas: false # in $
  base_buffer: 0.1 # relative to wealth
  concentration_limit: 0.5
  initial_wealth: 1000000
  solver_params:
    solver: "ECOS"
    verbose: false
    warm_start: false
    max_iters: 100
    abstol: 1
    reltol: 0.01
    feastol: 0.01
backtest:
  start_date: '2023-02-21T00:00:00'
  end_date: '2023-08-21T00:00:00'
