input_data:
  ResearchName: defillama
  dirpath:
  - data
  - DynLst
  selected_instruments: # this comes from top n ever
  - "42c02674-f7a2-4cb0-be3d-ade268838770" # balancer-v2_RETH-WETH
  - "4cc5df76-f81d-49fe-9e1e-4caa6a8dad0b" # balancer-v2_WSTETH-WETH
  - "6d342d6a-9796-443e-8152-b94e8b6021fc" # convex-finance_ETH-FRXETH
  - "747c1d2a-c668-4682-b9f9-296708a3dd90" # lido_STETH
  - "77020688-e1f9-443c-9388-e51ace15cc32" # frax-ether_SFRXETH
  - "98463e86-e32c-4998-830c-ccd47dbb3041" # aura_WSTETH-WETH
  - "a4b5b995-99e7-4b8f-916d-8940b5627d70" # aura_RETH-WETH
  - "c9873dab-0979-478c-b48c-3c3a0c935449" # convex-finance_STETH-FRXETH
  - "ce70e358-6668-498c-9afa-651f770eac27" # aura_WSTETH-SFRXETH-RETH
  - "d4b3c522-6127-4b89-bedf-83641cdcd2eb" # rocket-pool_RETH
  - "e378a7c2-6285-4993-9397-87ac9c8adc15" # convex-finance_ETH-STETH
  - "e6435aae-cbe9-4d26-ab2c-a4d533db9972" # aave-v3_WSTETH
  - "f1a22245-a1f1-4389-8ff2-dde4914b272d" # aave-v3_RETH
  - "fc7701fc-e290-4606-a8be-9e4ba6c5f91a" # convex-finance_ETH-RETH
  start_date: '2022-09-15T00:00:00'
run_parameters:
  normalize: false
  cross_ewma: false
  groupby: false
  models:
    apy:
      TrivialEwmPredictor:
        params:
          cap: 3 # stdev threshold of outlier yield
          halflife: 7d # ewm window for prediction
  pickle_file: engine.pickle
  unit_test: false
feature_map: # each feature present here will be transformed. times are in days.
  apy:
    as_is:
label_map:
  apy:
    horizons: # only first is used for now
    - 28
strategy:
  cost: 0.0005 # 1e-4 is a bp
  gas: false # in $
  base_buffer: 0.1 # relative to wealth
  concentration_limit: 0.4
  initial_wealth: 1000000
  solver_params:
    solver: "ECOS"
    verbose: false
    warm_start: false
    max_iters: 1000
    abstol: 0.01
    reltol: 0.01
    feastol: 0.01
backtest:
  start_date: '2022-09-01T00:00:00'
  end_date: '2023-09-01T00:00:00'
