input_data:
  ResearchName: defillama
  dirpath:
  - singularity
  - midfreq
  - data
  - DynYieldB
  selected_instruments: # this comes from top n ever
  - "282baaa9-11ef-4e72-8ade-efe0c43c07cc" # pancakeswap-amm-v3_USDT-USDC
  - "89eba1e5-1b1b-47b6-958b-38138a04c244" # venus_USDC
  - "8e1300db-21a5-4a27-bf3f-5788236df4eb" # radiant-v2_USDT
  - "92927cf2-f501-448c-8ed9-fb41b19e4efc" # radiant-v2_USDC
  - "9f3a6015-5045-4471-ba65-ad3dc7c38269" # venus_USDT
  - "a2e7bb87-b339-44d9-91d7-87a04552afe9" # stargate_USDT
  - "b2e9d5fe-19ca-456b-8cd5-c296d635136f" # pancakeswap-amm-v3_USDT-USDC
  start_date: '2022-09-15T00:00:00'
run_parameters:
  normalize: false
  cross_ewma: false
  groupby: false
  models:
    apy:
      TrivialEwmPredictor:
        params:
          cap: 3 # stdev threshold of outlier yield
          halflife: 7d # ewm window for prediction
  pickle_file: engine.pickle
  unit_test: false
feature_map: # each feature present here will be transformed. times are in days.
  apy:
    as_is:
label_map:
  apy:
    horizons: # only first is used for now
      - 28
strategy:
  cost: 0.0005 # 1e-4 is a bp
  gas: false # in $
  base_buffer: 0.1 # relative to wealth
  concentration_limit: 0.7
  initial_wealth: 1000000
  solver_params:
    solver: "ECOS"
    verbose: false
    warm_start: false
    max_iters: 1000
    abstol: 0.01
    reltol: 0.01
    feastol: 0.01
backtest:
  start_date: '2022-09-01T00:00:00'
  end_date: '2023-09-01T00:00:00'