- backtest.end_date: '1D'
  backtest.start_date: '180D'
  label_map.apy.horizons:
    - 5
  run_parameters.models.apy.TrivialEwmPredictor.params.cap: 3
  run_parameters.models.apy.TrivialEwmPredictor.params.halflife: 3d
  run_parameters.models.apy.TrivialEwmPredictor.params.horizon: 10d
  strategy.base_buffer: 0.05
  strategy.concentration_limit: 1.0
  strategy.cost: 0.0005
  strategy.gas: 1
  strategy.initial_wealth: 100000.0
- backtest.end_date: '1D'
  backtest.start_date: '180D'
  label_map.apy.horizons:
    - 5
  run_parameters.models.apy.TrivialEwmPredictor.params.cap: 3
  run_parameters.models.apy.TrivialEwmPredictor.params.halflife: 3d
  run_parameters.models.apy.TrivialEwmPredictor.params.horizon: 10d
  strategy.base_buffer: 0.05
  strategy.concentration_limit: 1.0
  strategy.cost: 0.0005
  strategy.gas: 1
  strategy.initial_wealth: 1000000.0
- backtest.end_date: '1D'
  backtest.start_date: '180D'
  label_map.apy.horizons:
    - 5
  run_parameters.models.apy.TrivialEwmPredictor.params.cap: 3
  run_parameters.models.apy.TrivialEwmPredictor.params.halflife: 3d
  run_parameters.models.apy.TrivialEwmPredictor.params.horizon: 10d
  strategy.base_buffer: 0.05
  strategy.concentration_limit: 1.0
  strategy.cost: 0.0005
  strategy.gas: 1
  strategy.initial_wealth: 10000000.0
- backtest.end_date: '1D'
  backtest.start_date: '180D'
  label_map.apy.horizons:
    - 10
  run_parameters.models.apy.TrivialEwmPredictor.params.cap: 3
  run_parameters.models.apy.TrivialEwmPredictor.params.halflife: 5d
  run_parameters.models.apy.TrivialEwmPredictor.params.horizon: 10d
  strategy.base_buffer: 0.05
  strategy.concentration_limit: 1.0
  strategy.cost: 0.0005
  strategy.gas: 1
  strategy.initial_wealth: 100000.0
- backtest.end_date: '1D'
  backtest.start_date: '180D'
  label_map.apy.horizons:
    - 10
  run_parameters.models.apy.TrivialEwmPredictor.params.cap: 3
  run_parameters.models.apy.TrivialEwmPredictor.params.halflife: 5d
  run_parameters.models.apy.TrivialEwmPredictor.params.horizon: 10d
  strategy.base_buffer: 0.05
  strategy.concentration_limit: 1.0
  strategy.cost: 0.0005
  strategy.gas: 1
  strategy.initial_wealth: 1000000.0
- backtest.end_date: '1D'
  backtest.start_date: '180D'
  label_map.apy.horizons:
    - 10
  run_parameters.models.apy.TrivialEwmPredictor.params.cap: 3
  run_parameters.models.apy.TrivialEwmPredictor.params.halflife: 5d
  run_parameters.models.apy.TrivialEwmPredictor.params.horizon: 10d
  strategy.base_buffer: 0.05
  strategy.concentration_limit: 1.0
  strategy.cost: 0.0005
  strategy.gas: 1
  strategy.initial_wealth: 10000000.0
- backtest.end_date: '1D'
  backtest.start_date: '180D'
  label_map.apy.horizons:
    - 10
  run_parameters.models.apy.TrivialEwmPredictor.params.cap: 3
  run_parameters.models.apy.TrivialEwmPredictor.params.halflife: 3d
  run_parameters.models.apy.TrivialEwmPredictor.params.horizon: 10d
  strategy.base_buffer: 0.05
  strategy.concentration_limit: 1.0
  strategy.cost: 0.0005
  strategy.gas: 1
  strategy.initial_wealth: 100000.0
- backtest.end_date: '1D'
  backtest.start_date: '180D'
  label_map.apy.horizons:
    - 10
  run_parameters.models.apy.TrivialEwmPredictor.params.cap: 3
  run_parameters.models.apy.TrivialEwmPredictor.params.halflife: 3d
  run_parameters.models.apy.TrivialEwmPredictor.params.horizon: 10d
  strategy.base_buffer: 0.05
  strategy.concentration_limit: 1.0
  strategy.cost: 0.0005
  strategy.gas: 1
  strategy.initial_wealth: 1000000.0
- backtest.end_date: '1D'
  backtest.start_date: '180D'
  label_map.apy.horizons:
    - 10
  run_parameters.models.apy.TrivialEwmPredictor.params.cap: 3
  run_parameters.models.apy.TrivialEwmPredictor.params.halflife: 3d
  run_parameters.models.apy.TrivialEwmPredictor.params.horizon: 10d
  strategy.base_buffer: 0.05
  strategy.concentration_limit: 1.0
  strategy.cost: 0.0005
  strategy.gas: 1
  strategy.initial_wealth: 10000000.0