protocols:
  tier1:
  - curve-dex
  - balancer
  - spark
  - sushiswap
  - sushiswap-v3
  - aave-v2
  - morpho-aavev3
  - uniswap-v2
  - lido
  - morpho-compound
  - compound-v3
  - morpho-aave
  - curve-finance
  - convex-finance
  - compound
  - frax-ether
  - aura
  #- makerdao #makerdao has no underlying in defillamma...
  - balancer-v2
  - rocket-pool
  - aave-v3
  - uniswap-v3
  - pancakeswap-amm
  - pancakeswap-amm-v3
  - merkl
  - beefy
  tier2:
  - venus-isolated-pools
  - thena-v1
  - venus-core-pool
  - stargate
  - abracadabra
oracle: none