underlyings:
  - usdt
  - usdc
  - usdc.e
  - dai
  - frax
  - lusd
  - mim
  - susd
  - fraxbp
  - mkusd
  - dola
protocols:
  - curve-dex
  - balancer
  - pancakeswap-amm
  - venus-isolated-pools
  - lido
  - aave-v2
  - morpho-aavev3
  - uniswap-v2
  - thena-v1
  - morpho-compound
  - compound-v3
  - morpho-aave
  - curve-finance
  - convex-finance
  - compound
  - frax-ether
  - aura
  - venus-core-pool
  - aave-v3
  - uniswap-v3
  - stargate
  - makerdao
  - balancer-v2
  - rocket-pool
  - pancakeswap-amm-v3
  - spark
  - extra-finance
